[package]
name = "chebyshevs_polynoms"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"
ndarray = "0.15"
ndarray-linalg = { version = "0.16", features = ["openblas"] }
integration = "0.1"
quad = "0.2"
ode = "0.3"
